# -*- coding: utf-8 -*-
"""Copy of LE1_stack_using_arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjSxtFS5rOk48HiOrZhvT-zPovWc-_BA
"""

# Lab Exercise - 1

# Implementing Stacks using Arrays 

class StackArrays:
    
    # Constructor for StackArrays class
    def __init__(self):
        # your code here
        self.stack = []
        

    # Push: Add an element to the top of the stack
    def push(self, element):
        # your code here
        self.stack.append(element)


    # Pop: Remove the topmost element in the stack and remove it
    def pop(self):
        # your code here
        if not self.isEmpty():
          return self.stack.pop()
        else:
          return -1


    # Returns the size of the stack
    def size(self):
        # your code here
        return len(self.stack)


    # Return the element at the top of the stack without removing it
    def top(self):
        # your code here
        if not self.isEmpty():
          return self.stack[-1]
        else:
          return -1

    # Returns True is stack is empty, False if not
    def isEmpty(self):
        # your code here
        if self.size() > 0:
          return False
        return True